# Generated by Django 4.2 on 2025-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to='models')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_store',
                'ordering': ['id'],
            },
        ),
    ]
