# Generated by Django 4.2 on 2025-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_algo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstore',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models'),
        ),
    ]
