# Generated by Django 4.2 on 2025-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_algo', '0002_alter_modelstore_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstore',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
