# Generated by Django 4.2 on 2025-04-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_algo', '0003_alter_modelstore_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLabel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_id', models.IntegerField()),
                ('label_name', models.CharField(max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection_algo.modelstore')),
            ],
            options={
                'db_table': 'model_label',
                'ordering': ['model_name'],
            },
        ),
    ]
