# Generated by Django 4.2 on 2025-04-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_algo', '0004_modellabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modellabel',
            options={'ordering': ['model_name', 'label_id']},
        ),
        migrations.AlterField(
            model_name='modellabel',
            name='label_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modellabel',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='detection_algo.modelstore'),
        ),
        migrations.AlterUniqueTogether(
            name='modellabel',
            unique_together={('model_name', 'label_id')},
        ),
    ]
